// create/templates/svelte/pages/dynamic-route.svelte
<Page>
  <Navbar title="Dynamic Route" backLink="Back" />
  <Block strong inset>
    <ul>
      <li><b>Url:</b> {f7route.url}</li>
      <li><b>Path:</b> {f7route.path}</li>
      <li><b>Hash:</b> {f7route.hash}</li>
      <li><b>Params:</b>
        <ul>
          {#each Object.keys(f7route.params) as key}
            <li><b>{key}:</b> {f7route.params[key]}</li>
          {/each}
        </ul>
      </li>
      <li><b>Query:</b>
        <ul>
          {#each Object.keys(f7route.query) as key}
            <li><b>{key}:</b> {f7route.query[key]}</li>
          {/each}
        </ul>
      </li>
      <li><b>Route:</b> {f7route.route.path}</li>
    </ul>
  </Block>
  <Block strong inset>
    <Link onClick={() => f7router.back()}>Go back via Router API</Link>
  </Block>
</Page>
<script>
  import { Page, Navbar, Block, Link } from 'framework7-svelte';

  export let f7route;
  export let f7router;
</script>

// create/templates/vue/pages/dynamic-route.vue
<template>
  <f7-page>
    <f7-navbar title="Dynamic Route" back-link></f7-navbar>
    <f7-block strong inset>
      <ul>
        <li><b>Url:</b> {{ f7route.url }}</li>
        <li><b>Path:</b> {{ f7route.path }}</li>
        <li><b>Hash:</b> {{ f7route.hash }}</li>
        <li>
          <b>Params:</b>
          <ul>
            <li v-for="(value, key) in f7route.params" :key="key">
              <b>{{ key }}:</b> {{ value }}
            </li>
          </ul>
        </li>
        <li>
          <b>Query:</b>
          <ul>
            <li v-for="(value, key) in f7route.query" :key="key">
              <b>{{ key }}:</b> {{ value }}
            </li>
          </ul>
        </li>
        <li><b>Route:</b> {{ f7route.route.path }}</li>
      </ul>
    </f7-block>
    <f7-block strong inset>
      <f7-link @click="f7router.back()">Go back via Router API</f7-link>
    </f7-block>
  </f7-page>
</template>
<script>
export default {
  props: {
    f7route: Object,
    f7router: Object,
  },
};
</script>
