// create/templates/react/pages/product.jsx
import React from 'react';
import { Page, Navbar, BlockTitle, Block, useStore } from 'framework7-react';

export default (props) => {
  const productId = props.f7route.params.id;
  const products = useStore('products');

  var currentProduct;
  products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
  return (
    <Page name="product">
      <Navbar title={currentProduct.title} backLink="Back" />
      <BlockTitle>About {currentProduct.title}</BlockTitle>
      <Block strong>
        {currentProduct.description}
      </Block>
    </Page>
  );
}

// create/templates/vue/pages/product.vue
<template>
  <f7-page name="product">
    <f7-navbar :title="product.title" back-link="Back"></f7-navbar>
    <f7-block-title>About {{product.title}}</f7-block-title>
    <f7-block strong>
      {{product.description}}
    </f7-block>
  </f7-page>
</template>
<script>
  import { useStore } from 'framework7-vue';

  export default {
    props: {
      f7route: Object,
    },
    setup(props) {
      const products = useStore('products');
      const productId = props.f7route.params.id;
      let currentProduct;
      products.forEach(function (product) {
        if (product.id === productId) {
          currentProduct = product;
        }
      });
      return {
        product: currentProduct,
      };
    },
  };
</script>
