// create/templates/svelte/pages/catalog.svelte
<Page name="catalog">
  <Navbar title="Catalog" />
  <List>
    {#each products as product, index (product.id)}
      <ListItem
        title={product.title}
        link={`/product/${product.id}/`}
      />
    {/each}
  </List>
</Page>
<script>
  import { f7ready, f7, Page, Navbar, List, ListItem } from 'framework7-svelte';

  let products = [];

  f7ready(() => {
    products = f7.data.products;
  });
</script>

// templates/vue/pages/catalog.vue
<template>
  <f7-page name="catalog">
    <f7-navbar title="Catalog"></f7-navbar>
    <f7-list>
      <f7-list-item
        v-for="(product) in products"
        :key="product.id"
        :title="product.title"
        :link="`/product/${product.id}/`"
      ></f7-list-item>
    </f7-list>
  </f7-page>
</template>
<script>
  export default {
    data: function () {
      return {
        products: this.$f7.data.products,
      };
    }
  };
</script>
