// create/templates/svelte/pages/left-page-2.svelte
<Page>
  <Navbar title="Left Page 2" backLink />
  <Block strong>
    <p>Maxime tempore, repellendus? Sequi saepe provident quas, neque assumenda dicta odit eaque nesciunt facere mollitia totam voluptate aspernatur vel corporis repudiandae commodi ad cumque repellendus. Saepe officia iure repellat repellendus.</p>
    <p>Ea maiores accusantium non fuga dicta, vero minus veniam! Ipsum eveniet vero voluptate veritatis aspernatur hic dicta adipisci, debitis. Sint quam aperiam repellat quis perspiciatis accusantium ipsum nulla soluta temporibus.</p>
    <p>Necessitatibus ipsum culpa doloremque, nostrum atque totam minima itaque! Blanditiis nobis nam repudiandae, ut nostrum voluptate accusantium atque, veniam libero quaerat corporis laborum earum rem nihil unde. Vitae cum, aliquam?</p>
    <p>Debitis aliquid nemo maxime recusandae, mollitia sed error vero. Atque molestiae rem necessitatibus nam voluptas quaerat, reiciendis, excepturi quis facilis, quod cupiditate vitae voluptate repudiandae! Unde impedit aut id ut?</p>
  </Block>
</Page>
<script>
  import { Page, Navbar, Block } from 'framework7-svelte';
</script>

// create/templates/react/pages/left-page-2.jsx
import React from 'react';
import { Page, Navbar, Block } from 'framework7-react';

const LeftPage2 = () => (
  <Page>
    <Navbar title="Left Page 2" backLink />
    <Block strong>
      <p>
        Maxime tempore, repellendus? Sequi saepe provident quas, neque assumenda dicta odit eaque
        nesciunt facere mollitia totam voluptate aspernatur vel corporis repudiandae commodi ad
        cumque repellendus. Saepe officia iure repellat repellendus.
      </p>
      <p>
        Ea maiores accusantium non fuga dicta, vero minus veniam! Ipsum eveniet vero voluptate
        veritatis aspernatur hic dicta adipisci, debitis. Sint quam aperiam repellat quis
        perspiciatis accusantium ipsum nulla soluta temporibus.
      </p>
      <p>
        Necessitatibus ipsum culpa doloremque, nostrum atque totam minima itaque! Blanditiis nobis
        nam repudiandae, ut nostrum voluptate accusantium atque, veniam libero quaerat corporis
        laborum earum rem nihil unde. Vitae cum, aliquam?
      </p>
      <p>
        Debitis aliquid nemo maxime recusandae, mollitia sed error vero. Atque molestiae rem
        necessitatibus nam voluptas quaerat, reiciendis, excepturi quis facilis, quod cupiditate
        vitae voluptate repudiandae! Unde impedit aut id ut?
      </p>
    </Block>
  </Page>
);

export default LeftPage2;
