// create-app/templates/svelte/pages/product.svelte
<Page name="product">
  <Navbar title={currentProduct.title} backLink="Back" />
  <BlockTitle>About {currentProduct.title}</BlockTitle>
  <Block strong>
    {currentProduct.description}
  </Block>
</Page>
<script>
  import { f7, Page, Navbar, BlockTitle, Block } from 'framework7-svelte';

  export let f7route;

  const productId = f7route.params.id;
  let currentProduct;
  f7.data.products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
</script>

// create/templates/react/pages/product.jsx
import React from 'react';
import { Page, Navbar, BlockTitle, Block, useStore } from 'framework7-react';

export default (props) => {
  const productId = props.f7route.params.id;
  const products = useStore('products');

  var currentProduct;
  products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
  return (
    <Page name="product">
      <Navbar title={currentProduct.title} backLink="Back" />
      <BlockTitle>About {currentProduct.title}</BlockTitle>
      <Block strong>
        {currentProduct.description}
      </Block>
    </Page>
  );
}
